# Generated by Django 5.2.5 on 2025-08-08 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('display', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool Category',
                'verbose_name_plural': 'Tool Categories',
                'db_table': 'tools_tool_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_authentication', models.BooleanField(default=False)),
                ('requires_host', models.BooleanField(default=False)),
                ('requires_api_key', models.BooleanField(default=False)),
                ('display', models.BooleanField(default=False)),
                ('documentation_url', models.URLField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='tool_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.toolcategory')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'db_table': 'tools_tool',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('host_name', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=500)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tools', to='tools.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Tool',
                'verbose_name_plural': 'User Tools',
                'db_table': 'tools_user_tool',
                'ordering': ['-last_used', 'tool__name'],
                'unique_together': {('user', 'tool')},
            },
        ),
    ]
