# Generated by Django 3.0.2 on 2022-01-30 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lit_reviews', '0022_auto_20220107_0953'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lit_reviews.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lit_review', 'Lit. Review'), ('CER', 'CER'), ('PMCF', 'PMCF')], default='lit_review', max_length=32)),
                ('initial_complated_date', models.DateField()),
                ('renewal_interval', models.IntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('library', models.ManyToManyField(to='client_portal.LibraryEntry')),
                ('lit_review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lit_reviews.LiteratureReview')),
                ('most_recent_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client_portal.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('version_short_name', models.CharField(editable=False, max_length=32)),
                ('date', models.DateField(auto_now=True)),
                ('comments', models.TextField()),
                ('comments_revision_file', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('final', 'final'), ('draft', 'draft'), ('pending_client_feedback', 'pending client feedback'), ('pending_corrections', 'pending corrections')], default='draft', max_length=32)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client_portal.Deliverable')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client_portal.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateField(auto_now_add=True)),
                ('message', models.TextField()),
                ('maybe', models.CharField(choices=[('message', 'message'), ('renewal', 'renewal'), ('vigilance', 'vigilance'), ('alert', 'alert')], default='message', max_length=32)),
                ('resolved_status', models.CharField(choices=[('read', 'read'), ('unread', 'unread'), ('hidden', 'hidden')], default='unread', max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client_portal.Project')),
            ],
        ),
    ]
