# Generated by Django 3.0.2 on 2022-02-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='maybe',
            new_name='type',
        ),
    ]
