# Generated by Django 3.0.2 on 2022-02-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0002_auto_20220216_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='share_drive_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='initial_complated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='library',
            field=models.ManyToManyField(blank=True, to='client_portal.LibraryEntry'),
        ),
    ]
