# Generated by Django 3.0.2 on 2022-02-21 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0025_merge_20220216_1652'),
        ('client_portal', '0003_auto_20220218_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.Client'),
        ),
    ]
