# Generated by Django 3.0.2 on 2022-02-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0003_auto_20220217_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='version_short_name',
            field=models.CharField(default=0, editable=False, max_length=32),
        ),
    ]
