# Generated by Django 3.0.2 on 2022-03-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0004_auto_20220221_2013'),
        ('client_portal', '0004_auto_20220222_1655'),
    ]

    operations = [
    ]
