# Generated by Django 3.0.2 on 2022-04-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0005_merge_20220303_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('lit_review', 'Lit. Review'), ('CER', 'CER'), ('PMCF', 'PMCF'), ('Vigilance', 'Vigilance')], default='lit_review', max_length=32),
        ),
    ]
