# Generated by Django 3.0.2 on 2022-05-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0006_auto_20220414_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='project name', max_length=100),
        ),
    ]
