# Generated by Django 3.0.2 on 2022-10-16 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0086_auto_20221016_1328'),
        ('client_portal', '0007_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryentry',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.Article'),
        ),
    ]
