# Generated by Django 3.0.2 on 2022-10-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0086_auto_20221016_1328'),
        ('client_portal', '0008_auto_20221016_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryentry',
            name='device',
            field=models.ManyToManyField(to='lit_reviews.Device'),
        ),
    ]
