# Generated by Django 3.0.2 on 2022-12-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0008_auto_20221016_1342'),
        ('client_portal', '0008_auto_20221021_1425'),
    ]

    operations = [
    ]
