# Generated by Django 3.0.2 on 2022-12-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0008_auto_20221021_1425'),
        ('client_portal', '0009_libraryentry_device'),
        ('client_portal', '0008_auto_20221002_1859'),
    ]

    operations = [
    ]
