# Generated by Django 3.0.2 on 2022-12-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0088_merge_20221205_1446'),
        ('client_portal', '0010_merge_20221205_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryentry',
            name='device',
        ),
        migrations.RemoveField(
            model_name='project',
            name='library',
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='project',
            field=models.ManyToManyField(to='client_portal.Project'),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.Article'),
        ),
    ]
