# Generated by Django 3.0.2 on 2022-12-05 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0088_merge_20221205_1446'),
        ('client_portal', '0011_auto_20221205_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryentry',
            name='project',
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='projects',
            field=models.ManyToManyField(related_name='library_entries', to='client_portal.Project'),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_entry', to='lit_reviews.Article'),
        ),
    ]
