# Generated by Django 3.0.2 on 2022-12-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0009_merge_20221201_1245'),
        ('client_portal', '0012_auto_20221205_1508'),
    ]

    operations = [
    ]
