# Generated by Django 3.0.2 on 2023-02-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0013_merge_20221207_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_hits',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='project',
            name='max_results',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='project',
            name='max_terms',
            field=models.IntegerField(default=15),
        ),
    ]
