# Generated by Django 3.0.2 on 2023-09-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0130_finallreportjob_comment'),
        ('client_portal', '0014_auto_20230201_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedSearchProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('deleted', 'deleted')], default='pending', max_length=32)),
                ('last_run_date', models.DateField(auto_now=True)),
                ('interval', models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly'), ('quarterly', 'quarterly'), ('annually', 'annually')], default='weekly', max_length=32)),
                ('terms', models.CharField(blank=True, max_length=1000, null=True)),
                ('terms_file', models.FileField(blank=True, null=True, upload_to='')),
                ('databases_to_search', models.ManyToManyField(blank=True, to='lit_reviews.NCBIDatabase')),
                ('lit_review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lit_reviews.LiteratureReview')),
            ],
        ),
    ]
