# Generated by Django 3.0.2 on 2023-09-03 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0130_finallreportjob_comment'),
        ('client_portal', '0015_automatedsearchproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedsearchproject',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.Client'),
            preserve_default=False,
        ),
    ]
