# Generated by Django 3.0.2 on 2023-09-10 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lit_reviews', '0130_finallreportjob_comment'),
        ('client_portal', '0016_automatedsearchproject_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedsearchproject',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending', max_length=32),
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=1000)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.Article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
