# Generated by Django 3.0.2 on 2023-10-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0017_auto_20230910_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedsearchproject',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
