# Generated by Django 3.0.2 on 2023-10-23 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0018_automatedsearchproject_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedSearchExcelReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
