# Generated by Django 3.0.2 on 2023-10-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0019_automatedsearchexcelreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedsearchexcelreport',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='automatedsearchexcelreport',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('EXCEL', 'EXCEL')], default='EXCEL', max_length=26),
        ),
        migrations.AlterField(
            model_name='automatedsearchexcelreport',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
