# Generated by Django 4.2 on 2024-11-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_portal", "0021_alter_action_id_alter_articlecomment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("lit_review", "Lit. Review"),
                    ("CER", "CER"),
                    ("PMCF", "PMCF"),
                    ("Vigilance", "Vigilance"),
                    ("Custom", "Custom"),
                ],
                default="lit_review",
                max_length=32,
            ),
        ),
    ]
