# Generated by Django 3.0.2 on 2022-01-13 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0022_auto_20220107_0953'),
        ('accounts', '0002_clientuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lit_reviews.Client', verbose_name='client'),
        ),
        migrations.DeleteModel(
            name='ClientUser',
        ),
    ]
