# Generated by Django 3.0.2 on 2022-01-14 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0022_auto_20220107_0953'),
        ('accounts', '0003_auto_20220113_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_expire_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lit_reviews.Client', verbose_name='client'),
        ),
    ]
