# Generated by Django 4.2 on 2024-07-18 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_first_name_alter_user_id_subscription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="company_name",
        ),
    ]
