# Generated by Django 4.2 on 2024-07-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_first_name_alter_user_id"),
        ("accounts", "0007_remove_profile_company_name"),
    ]

    operations = []
