# Generated by Django 4.2 on 2024-08-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_merge_20240719_1031"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_ops_member",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user is a member of our internal CiteMed operations team.",
                verbose_name="Operations team member",
            ),
        ),
    ]
