# Generated by Django 4.2 on 2025-01-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_ops_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan_credits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='remaining_credits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='licence_type',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('basic', 'Basic'), ('credits', 'Credits')], default='sandbox', max_length=255),
        ),
    ]
