# Generated by Django 4.2 on 2025-01-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_subscription_plan_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='remaining_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
