# Generated by Django 4.2 on 2025-04-20 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0206_merge_20250224_1942'),
        ('accounts', '0011_alter_subscription_plan_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(related_name='all_users', to='lit_reviews.client', verbose_name='Secondary companies user is part of'),
        ),
        migrations.AlterField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='lit_reviews.client', verbose_name='Main Company'),
        ),
    ]
