# Generated by Django 4.2 on 2025-04-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_subscription_plan_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='licence_type',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('basic', 'Basic'), ('credits', 'Credits'), ('unlimited', 'Unlimited')], default='sandbox', max_length=255),
        ),
    ]
