# Generated by Django 4.2 on 2025-04-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0207_alter_literaturereview_authorized_users_and_more'),
        ('accounts', '0012_user_companies_alter_user_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(blank=True, null=True, related_name='all_users', to='lit_reviews.client', verbose_name='Secondary companies user is part of'),
        ),
    ]
