# Generated by Django 4.2 on 2025-04-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_subscription_licence_type'),
        ('accounts', '0013_alter_user_companies'),
    ]

    operations = [
    ]
