# Generated by Django 4.2 on 2025-04-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20250421_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='licence_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('credits', 'Credits'), ('unlimited', 'Unlimited')], default='credits', max_length=255),
        ),
    ]
