# Generated by Django 5.2.5 on 2025-08-09 09:11

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='tools',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('gmap_tools', 'gmap_tools'), ('lucky_tools', 'lucky_tools')], max_length=50), blank=True, default=list, help_text='Select the tools to be use for the app.', size=None),
        ),
        migrations.AlterField(
            model_name='app',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access_app.requestaccesstier'),
        ),
    ]
