# Generated by Django 5.2.5 on 2025-08-10 02:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_app', '0002_app_tools_alter_app_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='tools',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('gmap_tools', 'GMAP_TOOLS'), ('lucky_tools', 'LUCKY_TOOLS')], max_length=50), blank=True, default=list, help_text='Select the tools to be use for the app.', size=None),
        ),
    ]
