# Generated by Django 5.2.5 on 2025-08-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_app', '0003_alter_app_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='schema_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='app',
            name='schema_name',
            field=models.CharField(blank=True, help_text='Description for API Schema.', max_length=100),
        ),
        migrations.AddField(
            model_name='app',
            name='schema_title',
            field=models.CharField(blank=True, help_text='Title of the API Schema.', max_length=100),
        ),
    ]
