# Generated by Django 3.0.2 on 2021-10-12 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lit_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereview',
            name='authorized_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
