# Generated by Django 3.0.2 on 2021-10-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0002_literaturereview_authorized_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturesearch',
            name='import_status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('INCOMPLETE-ERROR', 'INCOMPLETE-ERROR'), ('NOT RUN', 'NOT RUN')], default='NOT RUN', max_length=30),
        ),
        migrations.AddField(
            model_name='literaturesearch',
            name='imported_articles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='literaturesearch',
            name='processed_articles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='literaturesearch',
            name='search_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
