# Generated by Django 3.0.2 on 2021-11-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0003_auto_20211020_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adverseevent',
            name='db',
        ),
        migrations.RemoveField(
            model_name='adverseeventsearch',
            name='db',
        ),
        migrations.RemoveField(
            model_name='adverserecall',
            name='db',
        ),
        migrations.RemoveField(
            model_name='adverserecallsearch',
            name='db',
        ),
        migrations.AlterField(
            model_name='literaturesearch',
            name='import_status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('INCOMPLETE-ERROR', 'INCOMPLETE-ERROR'), ('NOT RUN', 'NOT RUN'), ('RUNNING', 'RUNNING')], default='NOT RUN', max_length=30),
        ),
    ]
