# Generated by Django 3.0.2 on 2021-11-18 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0004_auto_20211118_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdverseEventDatabase',
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.NCBIDatabase'),
        ),
        migrations.AddField(
            model_name='adverseeventsearch',
            name='db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.NCBIDatabase'),
        ),
        migrations.AddField(
            model_name='adverserecall',
            name='db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.NCBIDatabase'),
        ),
        migrations.AddField(
            model_name='adverserecallsearch',
            name='db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.NCBIDatabase'),
        ),
    ]
