# Generated by Django 3.0.2 on 2021-12-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0005_auto_20211118_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturesearch',
            name='script_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
