# Generated by Django 3.0.2 on 2021-12-05 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0006_literaturesearch_script_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adverserecallsearch',
            name='db',
        ),
        migrations.RemoveField(
            model_name='adverserecallsearch',
            name='literature_review',
        ),
        migrations.RemoveField(
            model_name='adverserecallsearch',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='adverserecallsearch',
            name='recalls',
        ),
        migrations.AddField(
            model_name='literaturesearch',
            name='ae_events',
            field=models.ManyToManyField(related_name='ae_events', to='lit_reviews.AdverseEvent'),
        ),
        migrations.AddField(
            model_name='literaturesearch',
            name='ae_recalls',
            field=models.ManyToManyField(related_name='ae_recalls', to='lit_reviews.AdverseRecall'),
        ),
        migrations.AlterField(
            model_name='adverseeventreview',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureSearch'),
        ),
        migrations.AlterField(
            model_name='adverserecallreview',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureSearch'),
        ),
        migrations.DeleteModel(
            name='AdverseEventSearch',
        ),
        migrations.DeleteModel(
            name='AdverseRecallSearch',
        ),
    ]
