# Generated by Django 3.0.2 on 2021-12-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0007_auto_20211205_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbidatabase',
            name='is_ae',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FinallReportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('INCOMPLETE-ERROR', 'INCOMPLETE-ERROR'), ('NOT RUN', 'NOT RUN'), ('RUNNING', 'RUNNING')], default='NOT RUN', max_length=30)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('appendix_a', models.FileField(blank=True, null=True, upload_to='')),
                ('appendix_b_all', models.FileField(blank=True, null=True, upload_to='')),
                ('appendix_b_retinc', models.FileField(blank=True, null=True, upload_to='')),
                ('appendix_c_all', models.FileField(blank=True, null=True, upload_to='')),
                ('appendix_c_retinc', models.FileField(blank=True, null=True, upload_to='')),
                ('appendix_d', models.FileField(blank=True, null=True, upload_to='')),
                ('appendix_e', models.FileField(blank=True, null=True, upload_to='')),
                ('prisma', models.TextField(blank=True, null=True)),
                ('literature_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureReview')),
            ],
        ),
    ]
