# Generated by Django 3.0.2 on 2021-12-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0008_auto_20211208_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finallreportjob',
            name='prisma',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
