# Generated by Django 3.0.2 on 2021-12-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0009_auto_20211208_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='job_started_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
