# Generated by Django 3.0.2 on 2021-12-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0010_finallreportjob_job_started_time'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='finallreportjob',
        #    name='verification_zip',
        #    field=models.FileField(blank=True, null=True, upload_to=''),
        #),
        migrations.AlterField(
            model_name='article',
            name='citation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exclusionreason',
            name='literature_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclustion_reasons', to='lit_reviews.LiteratureReview'),
        ),
        migrations.AlterField(
            model_name='literaturesearch',
            name='ae_events',
            field=models.ManyToManyField(blank=True, related_name='ae_events', to='lit_reviews.AdverseEvent'),
        ),
        migrations.AlterField(
            model_name='literaturesearch',
            name='ae_recalls',
            field=models.ManyToManyField(blank=True, related_name='ae_recalls', to='lit_reviews.AdverseRecall'),
        ),
        migrations.AlterField(
            model_name='literaturesearch',
            name='script_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
