# Generated by Django 3.0.2 on 2021-12-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0011_auto_20211214_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='fulltext_zip',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
