# Generated by Django 3.0.2 on 2021-12-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0012_finallreportjob_fulltext_zip'),
        ('lit_reviews', '0011_auto_20211214_0201'),
    ]

    operations = [
    ]
