# Generated by Django 3.0.2 on 2021-12-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0013_merge_20211219_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='adverse_events_short',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='guidance_short',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='objective_short',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='other_short',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='performance_short',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='safety_short',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='sota_short',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='study_conclusions_short',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='study_design_short',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='total_sample_size_short',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='treatment_modality_short',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        #migrations.AddField(
        #    model_name='finallreportjob',
        #    name='verification_zip',
        #    field=models.FileField(blank=True, null=True, upload_to=''),
        #),
    ]
