# Generated by Django 3.0.2 on 2021-12-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0014_auto_20211219_0251'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='finallreportjob',
        #     name='verification_zip',
        #     field=models.FileField(blank=True, null=True, upload_to=''),
        # ),
    ]
