# Generated by Django 3.0.2 on 2021-12-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0016_adversedatabasesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbidatabase',
            name='is_recall',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
