# Generated by Django 3.0.2 on 2021-12-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0011_auto_20211215_1256'),
        ('lit_reviews', '0017_ncbidatabase_is_recall'),
    ]

    operations = [
    ]
