# Generated by Django 3.0.2 on 2021-12-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0018_merge_20211224_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverseeventreview',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adverseeventreview',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='adverseeventreview',
            name='severity',
            field=models.CharField(blank=True, max_length=112, null=True),
        ),
        migrations.AddField(
            model_name='adverseeventreview',
            name='type',
            field=models.CharField(blank=True, max_length=112, null=True),
        ),
        migrations.AddField(
            model_name='adverserecallreview',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adverserecallreview',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='adverserecallreview',
            name='severity',
            field=models.CharField(blank=True, max_length=112, null=True),
        ),
        migrations.AddField(
            model_name='adverserecallreview',
            name='type',
            field=models.CharField(blank=True, max_length=112, null=True),
        ),
    ]
