# Generated by Django 3.0.2 on 2021-12-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0019_auto_20211224_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseeventreview',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='adverserecallreview',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
