# Generated by Django 3.0.2 on 2022-01-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0020_auto_20211229_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adverseeventreview',
            name='link',
        ),
        migrations.RemoveField(
            model_name='adverseeventreview',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='adverseeventreview',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='adverseeventreview',
            name='type',
        ),
        migrations.RemoveField(
            model_name='adverserecallreview',
            name='link',
        ),
        migrations.RemoveField(
            model_name='adverserecallreview',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='adverserecallreview',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='adverserecallreview',
            name='type',
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='manual_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='manual_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='manual_severity',
            field=models.CharField(blank=True, max_length=112, null=True),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='manual_type',
            field=models.CharField(blank=True, max_length=112, null=True),
        ),
        migrations.AddField(
            model_name='adverserecall',
            name='manual_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adverserecall',
            name='manual_pdf',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='adverserecall',
            name='manual_severity',
            field=models.CharField(blank=True, max_length=112, null=True),
        ),
        migrations.AddField(
            model_name='adverserecall',
            name='manual_type',
            field=models.CharField(blank=True, max_length=112, null=True),
        ),
    ]
