# Generated by Django 3.0.2 on 2022-01-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0021_auto_20220107_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverserecall',
            name='recall_class',
            field=models.IntegerField(null=True),
        ),
    ]
