# Generated by Django 3.0.2 on 2022-02-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0022_auto_20220107_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereviewintake',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
