# Generated by Django 3.0.2 on 2022-02-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0022_auto_20220107_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTermsPropsSummaryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('job_started_time', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('RUNNING', 'RUNNING'), ('NOT RUN', 'NOT RUN'), ('INCOMPLETE-ERROR', 'INCOMPLETE-ERROR')], default='NOT RUN', max_length=30)),
                ('doc', models.FileField(blank=True, null=True, upload_to='')),
                ('literature_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureReview')),
            ],
        ),
    ]
