# Generated by Django 3.0.2 on 2022-02-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0023_searchtermspropssummaryreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchtermspropssummaryreport',
            name='job_started_time',
        ),
        migrations.AddField(
            model_name='searchtermspropssummaryreport',
            name='start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
