# Generated by Django 3.0.2 on 2022-02-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0023_literaturereviewintake_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literaturereviewintake',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='literaturereview',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
