# Generated by Django 3.0.2 on 2022-02-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0024_auto_20220212_1403'),
        ('lit_reviews', '0024_auto_20220210_1942'),
    ]

    operations = [
    ]
