# Generated by Django 3.0.2 on 2022-02-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0025_merge_20220216_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturereviewsearchproposal',
            name='term',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='literaturesearch',
            name='term',
            field=models.CharField(max_length=550),
        ),
    ]
