# Generated by Django 3.0.2 on 2022-02-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0026_auto_20220222_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturereviewsearchproposal',
            name='term',
            field=models.CharField(max_length=1050),
        ),
        migrations.AlterField(
            model_name='literaturesearch',
            name='term',
            field=models.CharField(max_length=1050),
        ),
    ]
