# Generated by Django 3.0.2 on 2022-03-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0027_auto_20220222_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlereview',
            name='processed_abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
