# Generated by Django 3.0.2 on 2022-03-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0028_articlereview_processed_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='event_uid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='manual_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='manufacturer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adverserecall',
            name='event_uid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adverserecall',
            name='firm_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adverserecall',
            name='manual_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='adverserecall',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adverserecall',
            name='recall_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adverserecall',
            name='trade_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
