# Generated by Django 3.0.2 on 2022-03-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0029_auto_20220301_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adverserecall',
            name='recall_class',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
