# Generated by Django 3.0.2 on 2022-03-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0030_auto_20220301_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTermValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('INCOMPLETE-ERROR', 'INCOMPLETE-ERROR'), ('NOT RUN', 'NOT RUN'), ('RUNNING', 'RUNNING')], default='NOT RUN', max_length=30)),
                ('error_msg', models.CharField(max_length=1024)),
                ('literature_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureReview')),
            ],
        ),
    ]
