# Generated by Django 3.0.2 on 2022-03-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0030_auto_20220301_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adverserecall',
            name='recall_class',
        ),
    ]
