# Generated by Django 3.0.2 on 2022-03-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0031_remove_adverserecall_recall_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverserecall',
            name='recall_class',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
