# Generated by Django 3.0.2 on 2022-03-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0032_adverserecall_recall_class'),
        ('lit_reviews', '0031_searchtermvalidator'),
    ]

    operations = [
    ]
