# Generated by Django 3.0.2 on 2022-03-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0033_merge_20220303_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiteratureReviewProject',
        ),
    ]
