# Generated by Django 3.0.2 on 2022-03-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0033_merge_20220303_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereviewproject',
            name='type',
            field=models.CharField(default='lit_review', max_length=256),
        ),
    ]
