# Generated by Django 3.0.2 on 2022-03-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0034_delete_literaturereviewproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseeventreview',
            name='state',
            field=models.CharField(choices=[('IN', 'Included'), ('SM', 'Similar'), ('EX', 'Excluded or not Relevant'), ('UN', 'Not Reviewed'), ('DU', 'Duplicate')], default='UN', max_length=2),
        ),
    ]
