# Generated by Django 3.0.2 on 2022-03-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0034_literaturereviewproject_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalReportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sota_suitability', models.BooleanField(default=True)),
                ('appropriate_device', models.BooleanField(default=True)),
                ('appropriate_application', models.BooleanField(default=True)),
                ('appropriate_patient_group', models.BooleanField(default=True)),
                ('acceptable_collation_choices', models.BooleanField(default=True)),
                ('data_contribution', models.BooleanField(default=True)),
                ('grade', models.BooleanField(default=True)),
                ('design_yn', models.BooleanField(default=True)),
                ('outcomes_yn', models.BooleanField(default=True)),
                ('followup_yn', models.BooleanField(default=True)),
                ('stats_yn', models.BooleanField(default=True)),
                ('study_size_yn', models.BooleanField(default=True)),
                ('clin_sig_yn', models.BooleanField(default=True)),
                ('clear_conc_yn', models.BooleanField(default=True)),
                ('safety', models.BooleanField(default=True)),
                ('performance', models.BooleanField(default=True)),
                ('adverse_events', models.BooleanField(default=True)),
                ('sota', models.BooleanField(default=True)),
                ('guidance', models.BooleanField(default=True)),
                ('other', models.BooleanField(default=True)),
                ('study_design', models.BooleanField(default=True)),
                ('total_sample_size', models.BooleanField(default=True)),
                ('objective', models.BooleanField(default=True)),
                ('treatment_modality', models.BooleanField(default=True)),
                ('study_conclusions', models.BooleanField(default=True)),
                ('outcome_measures', models.BooleanField(default=True)),
                ('appropriate_followup', models.BooleanField(default=True)),
                ('statistical_significance', models.BooleanField(default=True)),
                ('clinical_significance', models.BooleanField(default=True)),
                ('justification', models.BooleanField(default=True)),
                ('literature_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureReview')),
            ],
        ),
    ]
