# Generated by Django 3.0.2 on 2022-03-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0035_finalreportconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='vigilance_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='finalreportconfig',
            name='acceptable_collation_choices',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='finalreportconfig',
            name='appropriate_application',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='finalreportconfig',
            name='appropriate_device',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='finalreportconfig',
            name='appropriate_patient_group',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='finalreportconfig',
            name='clear_conc_yn',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='finalreportconfig',
            name='clin_sig_yn',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='finalreportconfig',
            name='design_yn',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='finalreportconfig',
            name='followup_yn',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='finalreportconfig',
            name='grade',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='finalreportconfig',
            name='outcomes_yn',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='finalreportconfig',
            name='sota_suitability',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='finalreportconfig',
            name='stats_yn',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='finalreportconfig',
            name='study_size_yn',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
