# Generated by Django 3.0.2 on 2022-03-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0036_auto_20220310_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finallreportjob',
            name='vigilance_report',
        ),
    ]
