# Generated by Django 3.0.2 on 2022-03-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0037_remove_finallreportjob_vigilance_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='vigilance_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
