# Generated by Django 3.0.2 on 2022-03-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0039_auto_20220310_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturesearch',
            name='ae_events',
            field=models.ManyToManyField(blank=True, related_name='ae_events', to='lit_reviews.AdverseEvent'),
        ),
    ]
