# Generated by Django 3.0.2 on 2022-04-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0040_auto_20220310_1944'),
        ('lit_reviews', '0035_auto_20220326_0156'),
    ]

    operations = [
    ]
