# Generated by Django 3.0.2 on 2022-04-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0041_merge_20220404_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverseevent',
            name='event_number_full',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='event_number_short',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='adverseeventreview',
            name='is_duplicate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
