# Generated by Django 3.0.2 on 2022-04-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0042_auto_20220404_0037'),
    ]

    operations = [
    ]
