# Generated by Django 3.0.2 on 2022-04-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0041_merge_20220405_1115'),
        ('lit_reviews', '0042_auto_20220404_0037'),
    ]

    operations = [
    ]
