# Generated by Django 3.0.2 on 2022-04-07 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0043_merge_20220407_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureReviewSearchProposalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=1050)),
                ('errors', models.TextField(null=True)),
                ('status', models.CharField(choices=[('UPDATED', 'UPDATED'), ('PROCESSING', 'PROCESSING'), ('FAILED', 'FAILED')], default='UPDATED', max_length=30)),
                ('literature_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureReview')),
            ],
        ),
    ]
