# Generated by Django 3.0.2 on 2022-04-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0043_merge_20220409_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtermvalidator',
            name='error_msg',
            field=models.CharField(max_length=10024),
        ),
    ]
