# Generated by Django 3.0.2 on 2022-04-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0044_auto_20220409_0217'),
        ('lit_reviews', '0043_merge_20220407_1337'),
    ]

    operations = [
    ]
