# Generated by Django 3.0.2 on 2022-04-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0045_merge_20220412_1231'),
        ('lit_reviews', '0044_literaturereviewsearchproposalreport'),
    ]

    operations = [
    ]
