# Generated by Django 3.0.2 on 2022-04-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0045_merge_20220412_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprotocol',
            name='vigilance_inclusion_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchprotocol',
            name='vigilcance_inclusion_manufacturers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
