# Generated by Django 3.0.2 on 2022-04-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0046_auto_20220414_1639'),
        ('lit_reviews', '0046_merge_20220419_1841'),
    ]

    operations = [
    ]
