# Generated by Django 3.0.2 on 2022-04-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0047_merge_20220423_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprotocol',
            name='ae_databases_to_search',
            field=models.ManyToManyField(related_name='searchprotocol_ae', to='lit_reviews.NCBIDatabase'),
        ),
        migrations.AddField(
            model_name='searchprotocol',
            name='lit_searches_databases_to_search',
            field=models.ManyToManyField(related_name='searchprotocol_lit_searches', to='lit_reviews.NCBIDatabase'),
        ),
        migrations.AddField(
            model_name='searchprotocol',
            name='years_back',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
