# Generated by Django 3.0.2 on 2022-04-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0049_auto_20220423_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchprotocol',
            name='ae_databases_to_search',
            field=models.ManyToManyField(related_name='searchprotocol_ae', to='lit_reviews.NCBIDatabase'),
        ),
        migrations.AlterField(
            model_name='searchprotocol',
            name='lit_searches_databases_to_search',
            field=models.ManyToManyField(related_name='searchprotocol_lit_searches', to='lit_reviews.NCBIDatabase'),
        ),
    ]
