# Generated by Django 3.0.2 on 2022-05-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0050_auto_20220423_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literaturereview',
            name='intake',
        ),
        migrations.AddField(
            model_name='finallreportjob',
            name='version_number',
            field=models.DecimalField(blank=True, decimal_places=1, default='1.0', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='ncbidatabase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchprotocol',
            name='ae_date_of_search',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchprotocol',
            name='ae_years_back',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchprotocol',
            name='comparator_devices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchprotocol',
            name='lit_date_of_search',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchprotocol',
            name='sota_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LiteratureReviewIntake',
        ),
    ]
