# Generated by Django 3.0.2 on 2022-05-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0050_auto_20220423_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturesearch',
            name='search_file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
