# Generated by Django 3.0.2 on 2022-05-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0051_auto_20220524_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchprotocol',
            name='equivalence_discussion_biological',
        ),
        migrations.RemoveField(
            model_name='searchprotocol',
            name='equivalence_discussion_clinical',
        ),
        migrations.RemoveField(
            model_name='searchprotocol',
            name='equivalence_discussion_technical',
        ),
    ]
