# Generated by Django 3.0.2 on 2022-05-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0052_auto_20220524_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbidatabase',
            name='search_strategy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
