# Generated by Django 3.0.2 on 2022-05-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0053_ncbidatabase_search_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='report_type',
            field=models.CharField(choices=[('PROTOCOL', 'PROTOCOL'), ('REPORT', 'REPORT')], default='REPORT', max_length=30),
        ),
    ]
