# Generated by Django 3.0.2 on 2022-05-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0054_finallreportjob_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='searchprotocol',
            name='sota_description',
            field=models.TextField(blank=True, default='[Device Name] (and associated components) as [to be filled in]. would be compared to the state-of-the-art (SoTA) [to be filled in]. (Or devices most commonly used to [intended use]).  A separate SoTA search would include the use of standard [to be filled in].', null=True),
        ),
    ]
