# Generated by Django 3.0.2 on 2022-05-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0054_finallreportjob_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='protocol',
            field=models.FileField(blank=True, null=True, upload_to=''),
        )
    ]
