# Generated by Django 3.0.2 on 2022-06-03 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0055_auto_20220526_1552'),
        ('lit_reviews', '0055_auto_20220530_1526'),
    ]

    operations = [
    ]
