# Generated by Django 3.0.2 on 2022-06-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0055_auto_20220530_1526'),
    ]

    operations = [
    ]
