# Generated by Django 3.0.2 on 2022-06-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0056_merge_20220603_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprotocol',
            name='max_result_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adverserecallreview',
            name='state',
            field=models.CharField(choices=[('IN', 'Included'), ('SM', 'Similar'), ('EX', 'Excluded or not Relevant'), ('UN', 'Not Reviewed'), ('DU', 'Duplicate')], default='UN', max_length=2),
        ),
    ]
