# Generated by Django 3.0.2 on 2022-06-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0051_literaturesearch_search_file_url'),
        ('lit_reviews', '0057_auto_20220603_0151'),
    ]

    operations = [
    ]
