# Generated by Django 3.0.2 on 2022-06-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0056_merge_20220602_0200'),
        ('lit_reviews', '0057_auto_20220603_0151'),
    ]

    operations = [
    ]
