# Generated by Django 3.0.2 on 2022-06-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0057_auto_20220603_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finallreportjob',
            name='literature_review',
        ),
        # migrations.AddField(
        #     model_name='searchprotocol',
        #     name='max_result_count',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
    ]
