# Generated by Django 3.0.2 on 2022-06-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0058_merge_20220606_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturesearch',
            name='error_msg',
            field=models.TextField(blank=True, null=True),
        )
    ]
