# Generated by Django 3.0.2 on 2022-06-03 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0058_auto_20220603_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='literature_review',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureReview'),
            preserve_default=False,
        ),
       

    ]
