# Generated by Django 3.0.2 on 2022-06-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('lit_reviews', '0059_auto_20220603_0222'),
        ('lit_reviews', '0058_merge_20220605_1027'),
    ]

    operations = [
    ]
