# Generated by Django 3.0.2 on 2022-06-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0060_searchprotocol_max_result_count'),
        ('lit_reviews', '0060_merge_20220606_1347'),
    ]

    operations = [
    ]
