# Generated by Django 3.0.2 on 2022-06-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0061_merge_20220608_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='appendix_e2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
