# Generated by Django 3.0.2 on 2022-06-10 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0059_auto_20220603_0222'),
        ('lit_reviews', '0062_finallreportjob_appendix_e2'),
    ]

    operations = [
    ]
