# Generated by Django 3.0.2 on 2022-06-14 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0063_merge_20220610_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereviewsearchproposal',
            name='literature_search',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureSearch'),
        ),
    ]
