# Generated by Django 3.0.2 on 2022-06-14 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0064_literaturereviewsearchproposal_literature_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereviewsearchproposalreport',
            name='search_proposal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='lit_reviews.LiteratureReviewSearchProposal'),
        ),
    ]
