# Generated by Django 3.0.2 on 2022-06-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0065_literaturereviewsearchproposalreport_search_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literaturereviewsearchproposalreport',
            name='search_proposal',
        ),
        migrations.AddField(
            model_name='literaturereviewsearchproposal',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_proposal', to='lit_reviews.LiteratureReviewSearchProposalReport'),
        ),
    ]
