# Generated by Django 3.0.2 on 2022-06-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0066_auto_20220614_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='db_dumps')),
            ],
        ),
    ]
