# Generated by Django 3.0.2 on 2022-06-19 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0066_auto_20220614_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdversDatabaseSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.NCBIDatabase')),
                ('literature_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureReview')),
            ],
        ),
    ]
