# Generated by Django 3.0.2 on 2022-06-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0067_databasedump'),
        ('lit_reviews', '0067_adversdatabasesummary'),
    ]

    operations = [
    ]
