# Generated by Django 3.0.2 on 2022-06-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0068_merge_20220627_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprotocol',
            name='other_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchprotocol',
            name='performance_claims',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchprotocol',
            name='safety_claims',
            field=models.TextField(blank=True, null=True),
        ),
    ]
