# Generated by Django 3.0.2 on 2022-06-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0068_merge_20220627_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprotocol',
            name='max_articles_reviewed',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
