# Generated by Django 3.0.2 on 2022-06-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0069_searchprotocol_max_articles_reviewed'),
        ('lit_reviews', '0069_auto_20220627_1737'),
    ]

    operations = [
    ]
