# Generated by Django 3.0.2 on 2022-07-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0071_auto_20220629_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='generte_zip_status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('INCOMPLETE-ERROR', 'INCOMPLETE-ERROR'), ('NOT RUN', 'NOT RUN'), ('RUNNING', 'RUNNING')], default='NOT RUN', max_length=30),
        ),
        migrations.AlterField(
            model_name='searchprotocol',
            name='max_articles_reviewed',
            field=models.IntegerField(default=100),
        ),
    ]
