# Generated by Django 3.0.2 on 2022-07-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0072_auto_20220704_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='generate_zip_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
