# Generated by Django 3.0.2 on 2022-07-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0073_finallreportjob_generate_zip_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturesearch',
            name='duplicate_articles',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
