# Generated by Django 3.0.2 on 2022-07-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0074_literaturesearch_duplicate_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturereviewsearchproposal',
            name='term',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='literaturereviewsearchproposalreport',
            name='term',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='literaturesearch',
            name='term',
            field=models.CharField(max_length=5000),
        ),
    ]
