# Generated by Django 3.0.2 on 2022-08-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0074_literaturesearch_duplicate_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='comparison_color',
            field=models.TextField(blank=True, default='#c7d7cf', null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='exclusion_color',
            field=models.TextField(blank=True, default='#ff0000', null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='intervention_color',
            field=models.TextField(blank=True, default='#d5cad0', null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='outcome_color',
            field=models.TextField(blank=True, default='#aec2d0', null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='population_color',
            field=models.TextField(blank=True, default='#ebe4c2', null=True),
        ),
        migrations.CreateModel(
            name='CustomKeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_kw', models.TextField(blank=True, null=True)),
                ('custom_kw_color', models.TextField(blank=True, default='#ffffff', null=True)),
                ('literature_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureReview')),
            ],
        ),
    ]
