# Generated by Django 3.0.2 on 2022-07-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0074_literaturesearch_duplicate_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprotocol',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
