# Generated by Django 3.0.2 on 2022-08-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0075_searchprotocol_scope'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdverseDatabaseSummary',
        ),
    ]
