# Generated by Django 3.0.2 on 2022-08-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0075_searchprotocol_scope'),
        ('lit_reviews', '0075_auto_20220731_1144'),
    ]

    operations = [
    ]
