# Generated by Django 3.0.2 on 2022-08-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0075_auto_20220802_1441'),
        ('lit_reviews', '0075_searchprotocol_scope'),
    ]

    operations = [
    ]
