# Generated by Django 3.0.2 on 2022-08-18 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0076_delete_adversedatabasesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseDatabaseSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lit_reviews.NCBIDatabase')),
                ('literature_review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lit_reviews.LiteratureReview')),
            ],
        ),
    ]
