# Generated by Django 3.0.2 on 2022-08-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0076_merge_20220806_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlereview',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
