# Generated by Django 3.0.2 on 2022-08-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0077_articlereview_score'),
        ('lit_reviews', '0075_auto_20220731_1144'),
    ]

    operations = [
    ]
