# Generated by Django 3.0.2 on 2022-08-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0078_merge_20220815_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlereview',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
