# Generated by Django 3.0.2 on 2022-08-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0077_adversedatabasesummary'),
        ('lit_reviews', '0076_merge_20220814_1007'),
        ('lit_reviews', '0079_auto_20220815_1648'),
    ]

    operations = [
    ]
