# Generated by Django 3.0.2 on 2022-08-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0080_merge_20220823_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchprotocol',
            name='ae_databases_to_search',
            field=models.ManyToManyField(blank=True, related_name='searchprotocol_ae', to='lit_reviews.NCBIDatabase'),
        ),
    ]
