# Generated by Django 3.0.2 on 2022-08-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0080_merge_20220823_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='second_pass_articles',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='report_type',
            field=models.CharField(choices=[('PROTOCOL', 'PROTOCOL'), ('REPORT', 'REPORT'), ('SECONDPASS', 'SECONDPASS')], default='REPORT', max_length=30),
        ),
    ]
