# Generated by Django 3.0.2 on 2022-09-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0076_merge_20220830_1451'),
        ('lit_reviews', '0081_auto_20220828_1906'),
        ('lit_reviews', '0081_auto_20220831_1441'),
    ]

    operations = [
    ]
