# Generated by Django 3.0.2 on 2022-09-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0082_merge_20220904_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finallreportjob',
            name='report_type',
            field=models.CharField(choices=[('PROTOCOL', 'PROTOCOL'), ('REPORT', 'REPORT'), ('SECONDPASS', 'SECONDPASS'), ('APPENDIX', 'APPENDIX')], default='REPORT', max_length=30),
        ),
    ]
