# Generated by Django 3.0.2 on 2022-09-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0083_auto_20220907_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finallreportjob',
            name='report_type',
            field=models.CharField(choices=[('PROTOCOL', 'PROTOCOL'), ('REPORT', 'REPORT'), ('SECONDPASS', 'SECONDPASS'), ('APPENDIX_E2', 'APPENDIX_E2')], default='REPORT', max_length=30),
        ),
    ]
