# Generated by Django 3.0.2 on 2022-10-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0084_auto_20220908_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_year',
            field=models.IntegerField(null=True),
        ),
    ]
