# Generated by Django 3.0.2 on 2022-09-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0084_auto_20220908_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlereview',
            name='exclusion_reason',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='exclusionreason',
            name='reason',
            field=models.TextField(max_length=2000),
        ),
    ]
