# Generated by Django 3.0.2 on 2022-10-31 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0084_auto_20220908_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureReviewConfigTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literature_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureReview')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('DROP_DOWN', 'Drop Down')], max_length=512)),
                ('value', models.TextField(null=True)),
                ('drop_down_values', models.TextField(null=True)),
                ('for_template', models.BooleanField(default=False)),
                ('clinical_appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.ClinicalLiteratureAppraisal')),
                ('template', models.ManyToManyField(related_name='extraction_fields', to='lit_reviews.LiteratureReviewConfigTemplate')),
            ],
        ),
    ]
