# Generated by Django 3.0.2 on 2022-09-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0084_auto_20220908_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturesearch',
            name='search_report',
            field=models.FileField(blank=True, help_text='Search Report is a zip file that contains search_file & the datanase instructions for a manual search', null=True, upload_to=''),
        ),
    ]
