# Generated by Django 3.0.2 on 2022-10-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0084_auto_20220908_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='missing_clinical_appraisals',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
