# Generated by Django 3.0.2 on 2022-11-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0084_auto_20220908_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprotocol',
            name='sota_product_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
