# Generated by Django 3.0.2 on 2022-10-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0084_auto_20220908_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprotocol',
            name='indication_of_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
