# Generated by Django 3.0.2 on 2022-11-10 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0085_literaturesearch_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturesearch',
            name='created_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
