# Generated by Django 3.0.2 on 2022-10-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0085_article_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_year',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
