# Generated by Django 3.0.2 on 2022-11-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0085_searchprotocol_indication_of_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchprotocol',
            old_name='indication_of_user',
            new_name='indication_of_use',
        ),
    ]
