# Generated by Django 3.0.2 on 2022-10-31 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0085_extractionfield_literaturereviewconfigtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturereviewconfigtemplate',
            name='literature_review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureReview'),
        ),
    ]
