# Generated by Django 3.0.2 on 2022-11-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0086_auto_20221016_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='full_text',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
    ]
