# Generated by Django 3.0.2 on 2022-11-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0086_auto_20221116_0946'),
        ('lit_reviews', '0085_searchprotocol_sota_product_name'),
    ]

    operations = [
    ]
