# Generated by Django 3.0.2 on 2022-10-31 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0086_auto_20221031_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionfield',
            name='clinical_appraisal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.ClinicalLiteratureAppraisal'),
        ),
    ]
