# Generated by Django 3.0.2 on 2022-12-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0087_merge_20221120_2301'),
        ('lit_reviews', '0085_literaturesearch_search_report'),
        ('lit_reviews', '0085_auto_20220915_1148'),
        ('lit_reviews', '0085_finallreportjob_missing_clinical_appraisals'),
        ('lit_reviews', '0085_literaturesearch_expected_result_count'),
        ('lit_reviews', '0086_auto_20221016_1328'),
        ('lit_reviews', '0085_searchprotocol_max_imported_search_results'),
    ]

    operations = [
    ]
