# Generated by Django 3.0.2 on 2022-11-01 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0088_auto_20221031_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionfield',
            name='template',
        ),
        migrations.AddField(
            model_name='extractionfield',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_fields', to='lit_reviews.LiteratureReviewConfigTemplate'),
        ),
    ]
