# Generated by Django 3.0.2 on 2022-12-06 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0088_merge_20221205_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlereview',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lit_reviews.Article'),
        ),
    ]
