# Generated by Django 3.0.2 on 2022-12-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0089_auto_20221206_1741'),
        ('lit_reviews', '0088_merge_20221201_1245'),
    ]

    operations = [
    ]
