# Generated by Django 3.0.2 on 2023-01-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0090_merge_20221207_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='device_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
