# Generated by Django 3.0.2 on 2023-01-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0090_merge_20221207_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='terms_summary_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
