# Generated by Django 3.0.2 on 2023-01-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0090_merge_20221207_0922'),
        ('lit_reviews', '0089_auto_20221101_1940'),
        ('lit_reviews', '0086_auto_20221110_1246'),
    ]

    operations = [
    ]
