# Generated by Django 3.0.2 on 2023-01-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0091_finallreportjob_terms_summary_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalliteratureappraisal',
            name='sota_exclusion_reason',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
