# Generated by Django 3.0.2 on 2023-01-25 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0091_finallreportjob_terms_summary_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('is_template', models.BooleanField(default=False, help_text='\n        Template search configuration is just a placeholder for the strandard configurations that will be included in every new projuct\n    ')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.NCBIDatabase')),
                ('literature_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureReview')),
            ],
        ),
        migrations.CreateModel(
            name='SearchParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('type', models.CharField(choices=[('TX', 'Text'), ('DP', 'Drop Down'), ('CK', 'Check Box')], max_length=512)),
                ('options', models.TextField()),
                ('value', models.CharField(max_length=1024)),
                ('search_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.SearchConfiguration')),
            ],
        ),
    ]
