# Generated by Django 3.0.2 on 2023-01-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0091_finallreportjob_terms_summary_report'),
        ('lit_reviews', '0091_clinicalliteratureappraisal_device_name'),
    ]

    operations = [
    ]
