# Generated by Django 3.0.2 on 2023-02-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0092_auto_20230126_0805'),
        ('lit_reviews', '0091_clinicalliteratureappraisal_device_name'),
    ]

    operations = [
    ]
