# Generated by Django 3.0.2 on 2023-01-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0092_searchconfiguration_searchparameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchconfiguration',
            name='name',
        ),
    ]
