# Generated by Django 3.0.2 on 2023-02-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0091_clinicalliteratureappraisal_device_name'),
        ('lit_reviews', '0092_auto_20230126_0805'),
    ]

    operations = [
    ]
