# Generated by Django 3.0.2 on 2023-01-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0093_remove_searchconfiguration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchparameter',
            name='search_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='lit_reviews.SearchConfiguration'),
        ),
    ]
