# Generated by Django 3.0.2 on 2023-01-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0094_auto_20230125_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchconfiguration',
            name='literature_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureReview'),
        ),
        migrations.AlterField(
            model_name='searchparameter',
            name='options',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='searchparameter',
            name='value',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
