# Generated by Django 3.0.2 on 2023-01-25 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0095_auto_20230125_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchconfiguration',
            name='literature_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_configurations', to='lit_reviews.LiteratureReview'),
        ),
    ]
