# Generated by Django 3.0.2 on 2023-01-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0096_auto_20230125_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchparameter',
            name='type',
            field=models.CharField(choices=[('TX', 'Text'), ('DP', 'Drop Down'), ('CK', 'Check Box'), ('DT', 'Date')], max_length=512),
        ),
        migrations.AlterField(
            model_name='searchparameter',
            name='value',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
