# Generated by Django 3.0.2 on 2023-01-29 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0097_auto_20230129_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchconfiguration',
            name='literature_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_configurations', to='lit_reviews.LiteratureReview'),
        ),
    ]
