# Generated by Django 3.0.2 on 2023-02-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0098_auto_20230129_1744'),
        ('lit_reviews', '0093_merge_20230205_1440'),
        ('lit_reviews', '0093_merge_20230201_1422'),
    ]

    operations = [
    ]
