# Generated by Django 3.0.2 on 2023-02-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0099_merge_20230211_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturesearch',
            name='disable_exclusion',
            field=models.BooleanField(default=False),
        ),
    ]
