# Generated by Django 3.0.2 on 2023-02-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0099_merge_20230206_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalliteratureappraisal',
            name='sota_exclusion_reason',
            field=models.CharField(blank=True, choices=[('NC', 'Describes technical or non-clinical study results only, including animal or cadaver studies'), ('OP', 'Contains unsubstantiated opinions'), ('KN', 'Do not represent the current knowledge/state of the art'), ('AG', 'The articles are not in line with the established time frame'), ('EN', 'Non-English Language'), ('PU', 'Publications types other than Peer reviewed guidelines, International peer reviewed consensus statements, State of the Art review (can be narrative review), systematic review, or Meta-Analysis')], max_length=2, null=True),
        ),
    ]
