# Generated by Django 3.0.2 on 2023-02-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0100_auto_20230206_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturesearch',
            name='search_file_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
