# Generated by Django 3.0.2 on 2023-02-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0092_merge_20230131_1110'),
        ('lit_reviews', '0101_auto_20230208_1309'),
        ('lit_reviews', '0099_merge_20230208_1842'),
    ]

    operations = [
    ]
