# Generated by Django 3.0.2 on 2023-02-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0102_merge_20230213_1437'),
        ('lit_reviews', '0101_auto_20230211_1149'),
    ]

    operations = [
    ]
