# Generated by Django 3.0.2 on 2023-03-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0103_merge_20230215_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverseevent',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
