# Generated by Django 3.0.2 on 2023-04-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0104_adverseevent_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='mdcg_ranking',
            field=models.CharField(blank=True, choices=[('Rank 01', 'Rank 01'), ('Rank 02', 'Rank 02'), ('Rank 03', 'Rank 03'), ('Rank 04', 'Rank 04'), ('Rank 05', 'Rank 05'), ('Rank 06', 'Rank 06'), ('Rank 07', 'Rank 07'), ('Rank 08', 'Rank 08'), ('Rank 09', 'Rank 09'), ('Rank 10', 'Rank 10'), ('Rank 11', 'Rank 11'), ('Rank 12', 'Rank 12')], max_length=126, null=True),
        ),
    ]
