# Generated by Django 3.0.2 on 2023-03-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0091_merge_20230130_1746'),
        ('lit_reviews', '0104_adverseevent_report_date'),
    ]

    operations = [
    ]
