# Generated by Django 3.0.2 on 2023-03-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0104_adverseevent_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprotocol',
            name='preparer',
            field=models.CharField(blank=True, default='Edward Drower, M.S.', max_length=256, null=True),
        ),
    ]
