# Generated by Django 3.0.2 on 2023-04-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0105_searchprotocol_preparer'),
        ('lit_reviews', '0105_clinicalliteratureappraisal_mdcg_ranking'),
    ]

    operations = [
    ]
