# Generated by Django 3.0.2 on 2023-04-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0106_merge_20230409_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchprotocol',
            name='preparer',
            field=models.CharField(blank=True, default='S. Senthil Kumar, Ph.D.', max_length=256, null=True),
        ),
    ]
