# Generated by Django 3.0.2 on 2023-04-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0107_auto_20230409_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='indication',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
