# Generated by Django 3.0.2 on 2023-04-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0108_clinicalliteratureappraisal_indication'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='all_articles_review',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='report_type',
            field=models.CharField(choices=[('PROTOCOL', 'PROTOCOL'), ('REPORT', 'REPORT'), ('SECONDPASS', 'SECONDPASS'), ('APPENDIX_E2', 'APPENDIX_E2'), ('ARTICLE_REVIEWS', 'ARTICLE_REVIEWS')], default='REPORT', max_length=30),
        ),
    ]
