# Generated by Django 3.0.2 on 2023-05-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0108_clinicalliteratureappraisal_indication'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbidatabase',
            name='displayed_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
