# Generated by Django 3.0.2 on 2023-05-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0109_auto_20230427_0631'),
        ('lit_reviews', '0105_merge_20230313_1006'),
    ]

    operations = [
    ]
