# Generated by Django 3.0.2 on 2023-05-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0109_auto_20230427_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchprotocol',
            name='max_imported_search_results',
            field=models.IntegerField(default=300),
        ),
    ]
