# Generated by Django 3.0.2 on 2023-05-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0109_auto_20230427_0631'),
        ('lit_reviews', '0089_auto_20221101_1940'),
    ]

    operations = [
    ]
