# Generated by Django 3.0.2 on 2023-05-14 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lit_reviews', '0109_auto_20230427_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('applied_filters', models.CharField(max_length=256, null=True)),
                ('search_term', models.CharField(max_length=1024)),
                ('database_name', models.CharField(max_length=126)),
                ('script_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=52)),
                ('results_file', models.URLField()),
                ('results_count', models.IntegerField()),
                ('errors', models.TextField()),
                ('warnings', models.TextField()),
                ('literature_review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lit_reviews.LiteratureReview')),
                ('search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lit_reviews.LiteratureSearch')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
