# Generated by Django 3.0.2 on 2023-05-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0109_auto_20230427_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchprotocol',
            old_name='vigilcance_inclusion_manufacturers',
            new_name='vigilance_inclusion_manufacturers',
        ),
    ]
