# Generated by Django 3.0.2 on 2023-05-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0109_auto_20230427_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='condensed_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='report_type',
            field=models.CharField(choices=[('PROTOCOL', 'PROTOCOL'), ('REPORT', 'REPORT'), ('CONDENSED_REPORT', 'CONDENSED_REPORT'), ('SECONDPASS', 'SECONDPASS'), ('APPENDIX_E2', 'APPENDIX_E2'), ('ARTICLE_REVIEWS', 'ARTICLE_REVIEWS')], default='REPORT', max_length=30),
        ),
    ]
