# Generated by Django 3.0.2 on 2023-05-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0109_ncbidatabase_displayed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncbidatabase',
            name='displayed_name',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
    ]
