# Generated by Django 3.0.2 on 2023-05-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0110_auto_20230501_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbidatabase',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived datrabase are not being used any more'),
        ),
    ]
