# Generated by Django 3.0.2 on 2023-05-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0110_auto_20230516_1155'),
        ('lit_reviews', '0110_auto_20230516_1505'),
    ]

    operations = [
    ]
