# Generated by Django 3.0.2 on 2023-05-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0110_merge_20230511_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionfield',
            name='category',
            field=models.CharField(choices=[('ST', 'Sutdy Design'), ('T', 'Treatment'), ('SR', 'Study Result')], default='ST', max_length=10),
        ),
    ]
