# Generated by Django 3.0.2 on 2023-05-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0110_scraperreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperreport',
            name='failure_stage_screenshot',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
