# Generated by Django 3.0.2 on 2023-05-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0111_scraperreport_failure_stage_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperreport',
            name='results_count',
        ),
        migrations.AddField(
            model_name='scraperreport',
            name='result_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scraperreport',
            name='results_file',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='scraperreport',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('EXCLUDED', 'EXCLUDED')], max_length=52),
        ),
    ]
