# Generated by Django 3.0.2 on 2023-05-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0111_extractionfield_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractionfield',
            old_name='for_template',
            new_name='is_template',
        ),
        migrations.RemoveField(
            model_name='extractionfield',
            name='template',
        ),
        migrations.AddField(
            model_name='extractionfield',
            name='literature_review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_fields', to='lit_reviews.LiteratureReview'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LiteratureReviewConfigTemplate',
        ),
    ]
