# Generated by Django 3.0.2 on 2023-05-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0112_auto_20230513_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionfield',
            name='clinical_appraisal',
        ),
        migrations.RemoveField(
            model_name='extractionfield',
            name='value',
        ),
        migrations.CreateModel(
            name='AppraisalExtractionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(null=True)),
                ('clinical_appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.ClinicalLiteratureAppraisal')),
                ('extraction_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apprailsal_extraction_fields', to='lit_reviews.LiteratureReview')),
            ],
        ),
    ]
