# Generated by Django 3.0.2 on 2023-05-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0113_auto_20230513_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalextractionfield',
            name='extraction_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apprailsal_extraction_fields', to='lit_reviews.ExtractionField'),
        ),
    ]
