# Generated by Django 3.0.2 on 2023-05-13 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0114_auto_20230513_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalextractionfield',
            name='clinical_appraisal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='lit_reviews.ClinicalLiteratureAppraisal'),
        ),
    ]
