# Generated by Django 3.0.2 on 2023-05-23 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0110_auto_20230516_1505'),
        ('lit_reviews', '0111_ncbidatabase_is_archived'),
        ('lit_reviews', '0112_auto_20230514_1220'),
        ('lit_reviews', '0110_auto_20230516_1155'),
        ('lit_reviews', '0115_auto_20230513_1435'),
    ]

    operations = [
    ]
