# Generated by Django 3.0.2 on 2023-05-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0116_merge_20230523_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbidatabase',
            name='instructions_for_search',
            field=models.URLField(blank=True, null=True),
        ),
    ]
