# Generated by Django 3.0.2 on 2023-05-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0111_merge_20230521_0953'),
        ('lit_reviews', '0117_ncbidatabase_instructions_for_search'),
    ]

    operations = [
    ]
