# Generated by Django 3.0.2 on 2023-05-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0110_auto_20230507_1212'),
        ('lit_reviews', '0118_merge_20230523_1152'),
    ]

    operations = [
    ]
