# Generated by Django 3.0.2 on 2023-05-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0119_merge_20230525_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionfield',
            name='category',
            field=models.CharField(choices=[('ST', 'Study Design'), ('T', 'Treatment'), ('SR', 'Study Result')], default='ST', max_length=10),
        ),
    ]
