# Generated by Django 3.0.2 on 2023-06-13 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0120_auto_20230531_1359'),
        ('lit_reviews', '0113_merge_20230521_1527'),
    ]

    operations = [
    ]
