# Generated by Django 3.0.2 on 2023-06-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0121_merge_20230613_0034'),
        ('lit_reviews', '0121_merge_20230612_1446'),
    ]

    operations = [
    ]
