# Generated by Django 3.0.2 on 2023-06-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0122_merge_20230615_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionfield',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('LONG_TEXT', 'Long Text'), ('DROP_DOWN', 'Drop Down')], max_length=512),
        ),
    ]
