# Generated by Django 3.0.2 on 2023-06-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0122_merge_20230615_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperreport',
            name='applied_filters',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scraperreport',
            name='search_term',
            field=models.TextField(),
        ),
    ]
