# Generated by Django 3.0.2 on 2023-06-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0110_merge_20230502_1504'),
        ('lit_reviews', '0123_auto_20230622_0902'),
    ]

    operations = [
    ]
