# Generated by Django 3.0.2 on 2023-07-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0123_auto_20230622_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='classification',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='markets',
            field=models.CharField(default='TBD', max_length=250),
            preserve_default=False,
        ),
    ]
