# Generated by Django 3.0.2 on 2023-07-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0123_auto_20230621_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionfield',
            name='field_section',
            field=models.CharField(choices=[('SO', 'Suitability and Outcomes (All Articles including SoTA)'), ('QC', 'Quality and Contribution Questions'), ('MR', 'MDCG Ranking'), ('EF', 'Extraction Fields'), ('ST', 'SoTa')], default='EF', max_length=10),
        ),
    ]
