# Generated by Django 3.0.2 on 2023-07-19 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0124_auto_20230706_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='literature_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lit_reviews.LiteratureReview'),
        ),
    ]
