# Generated by Django 3.0.2 on 2023-07-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0086_auto_20221110_1246'),
        ('lit_reviews', '0124_auto_20230706_0848'),
    ]

    operations = [
    ]
