# Generated by Django 3.0.2 on 2023-07-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0124_auto_20230706_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbidatabase',
            name='export_file_format',
            field=models.CharField(blank=True, help_text='File format for the search results exported file to be uploaded in the app', max_length=256, null=True),
        ),
    ]
