# Generated by Django 3.0.2 on 2023-07-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0124_extractionfield_field_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionfield',
            name='description',
            field=models.TextField(help_text='A descriptive label that will be shown in the form', null=True),
        ),
    ]
