# Generated by Django 3.0.2 on 2023-07-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0124_auto_20230706_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturereviewsearchproposal',
            name='years_back',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='literaturesearch',
            name='years_back',
            field=models.FloatField(null=True),
        ),
    ]
