# Generated by Django 3.0.2 on 2023-07-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0125_extractionfield_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionfield',
            name='name_in_report',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
