# Generated by Django 3.0.2 on 2023-07-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0125_auto_20230718_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturereviewsearchproposal',
            name='years_back',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='literaturesearch',
            name='years_back',
            field=models.FloatField(default=10),
        ),
    ]
