# Generated by Django 3.0.2 on 2023-07-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0125_article_literature_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pmc_uid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pubmed_uid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
