# Generated by Django 3.0.2 on 2023-07-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0126_extractionfield_name_in_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionfield',
            name='field_order',
            field=models.IntegerField(null=True),
        ),
    ]
