# Generated by Django 3.0.2 on 2023-07-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0127_extractionfield_field_order'),
        ('lit_reviews', '0126_auto_20230719_1943'),
        ('lit_reviews', '0125_ncbidatabase_export_file_format'),
        ('lit_reviews', '0125_merge_20230725_1107'),
        ('lit_reviews', '0126_auto_20230718_2045'),
    ]

    operations = [
    ]
