# Generated by Django 3.0.2 on 2023-07-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0128_merge_20230726_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionfield',
            name='description',
            field=models.TextField(blank=True, help_text='A descriptive label that will be shown in the form', null=True),
        ),
        migrations.AlterField(
            model_name='extractionfield',
            name='name_in_report',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='extractionfield',
            unique_together={('name', 'literature_review')},
        ),
    ]
