# Generated by Django 3.0.2 on 2023-08-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0129_auto_20230728_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
