# Generated by Django 3.0.2 on 2023-11-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0129_auto_20230728_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='app_status',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
