# Generated by Django 3.0.2 on 2023-08-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0129_auto_20230728_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTermPreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], max_length=32)),
                ('errors', models.TextField(null=True)),
                ('literature_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.LiteratureSearch')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('abstract', models.TextField()),
                ('citation', models.TextField()),
                ('preview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.SearchTermPreview')),
            ],
        ),
    ]
