# Generated by Django 3.0.2 on 2023-09-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0130_finallreportjob_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereview',
            name='is_autosearch',
            field=models.BooleanField(default=False, help_text='Auto Search Project are only for testing different search terms and check thier results'),
        ),
    ]
