# Generated by Django 3.0.2 on 2023-09-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0130_finallreportjob_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finallreportjob',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
