# Generated by Django 3.0.2 on 2023-08-23 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lit_reviews', '0130_articlepreview_searchtermpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtermpreview',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlepreview',
            name='preview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_articles', to='lit_reviews.SearchTermPreview'),
        ),
    ]
