# Generated by Django 3.0.2 on 2023-11-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0130_clinicalliteratureappraisal_app_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalliteratureappraisal',
            name='app_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
