# Generated by Django 3.0.2 on 2023-08-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0131_auto_20230823_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepreview',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='articlepreview',
            name='citation',
            field=models.TextField(null=True),
        ),
    ]
