# Generated by Django 3.0.2 on 2023-09-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0131_literaturereview_is_autosearch'),
        ('lit_reviews', '0132_auto_20230824_1604'),
        ('lit_reviews', '0131_auto_20230912_1804'),
    ]

    operations = [
    ]
