# Generated by Django 3.0.2 on 2023-12-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0133_merge_20230919_1210'),
        ('lit_reviews', '0131_auto_20231115_1311'),
    ]

    operations = [
    ]
