# Generated by Django 3.0.2 on 2023-10-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0133_merge_20230919_1210'),
        ('lit_reviews', '0124_merge_20230625_1513'),
    ]

    operations = [
    ]
