# Generated by Django 3.0.2 on 2023-10-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0133_merge_20230919_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturesearch',
            name='end_search_interval',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='literaturesearch',
            name='start_search_interval',
            field=models.DateField(null=True),
        ),
    ]
