# Generated by Django 3.0.2 on 2023-12-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0134_merge_20231201_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprotocol',
            name='ae_end_date_of_search',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchprotocol',
            name='lit_end_date_of_search',
            field=models.DateField(blank=True, null=True),
        ),
    ]
