# Generated by Django 3.0.2 on 2023-10-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0134_auto_20231005_1634'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='literaturesearch',
            name='unique_term_source',
        ),
        migrations.AddConstraint(
            model_name='literaturesearch',
            constraint=models.UniqueConstraint(fields=('literature_review', 'term', 'db', 'start_search_interval'), name='unique_term_source'),
        ),
        migrations.AddConstraint(
            model_name='literaturesearch',
            constraint=models.UniqueConstraint(condition=models.Q(start_search_interval__isnull=True), fields=('literature_review', 'term', 'db'), name='unique_term_source2'),
        ),
    ]
