# Generated by Django 3.0.2 on 2023-10-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0134_merge_20231005_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='highlighted_full_text',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
    ]
