# Generated by Django 3.0.2 on 2023-12-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0135_auto_20231008_1505'),
        ('lit_reviews', '0135_searchtermpreview_results'),
        ('lit_reviews', '0135_auto_20231201_1013'),
    ]

    operations = [
    ]
