# Generated by Django 3.0.2 on 2023-12-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0136_merge_20231202_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchprotocol',
            old_name='ae_end_date_of_search',
            new_name='ae_start_date_of_search',
        ),
        migrations.RenameField(
            model_name='searchprotocol',
            old_name='lit_end_date_of_search',
            new_name='lit_start_date_of_search',
        ),
    ]
