# Generated by Django 3.0.2 on 2023-12-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0137_auto_20231202_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlereview',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
