# Generated by Django 3.0.2 on 2023-12-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0138_articlereview_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturesearch',
            name='end_search_interval',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='literaturesearch',
            name='start_search_interval',
            field=models.DateField(blank=True, null=True),
        ),
    ]
