# Generated by Django 3.0.2 on 2023-12-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0139_auto_20231211_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturesearch',
            name='search_report_failing_msg',
            field=models.CharField(blank=True, help_text='If Search Report Generation fails the error message will bestored here', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='searchprotocol',
            name='scope',
            field=models.TextField(blank=True, default='The scope of the literature search includes a query of select adverse event report databases as well as scientific databases for the date range starting from [startdate] to [end date]. This period of time is felt to provide sufficient clinical experience with these devices from both a safety and performance perspective. Performance assessments include reports designed to....[ finish the paragraph below ]', null=True),
        ),
    ]
