# Generated by Django 3.0.2 on 2023-12-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0139_auto_20231211_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereview',
            name='review_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('SIMPLE', 'Simple')], default='STANDARD', max_length=126),
        ),
        migrations.AlterField(
            model_name='literaturereview',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lit_reviews.Device'),
        ),
        migrations.AlterField(
            model_name='searchprotocol',
            name='scope',
            field=models.TextField(blank=True, default='The scope of the literature search includes a query of select adverse event report databases as well as scientific databases for the date range starting from [startdate] to [end date]. This period of time is felt to provide sufficient clinical experience with these devices from both a safety and performance perspective. Performance assessments include reports designed to....[ finish the paragraph below ]', null=True),
        ),
    ]
