# Generated by Django 3.0.2 on 2023-12-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0140_auto_20231220_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finallreportjob',
            name='report_type',
            field=models.CharField(choices=[('PROTOCOL', 'PROTOCOL'), ('REPORT', 'REPORT'), ('CONDENSED_REPORT', 'CONDENSED_REPORT'), ('SECONDPASS', 'SECONDPASS'), ('APPENDIX_E2', 'APPENDIX_E2'), ('ARTICLE_REVIEWS', 'ARTICLE_REVIEWS'), ('PRISMA', 'PRISMA')], default='REPORT', max_length=30),
        ),
        migrations.AlterField(
            model_name='literaturereview',
            name='review_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('SIMPLE', 'Streamline')], default='STANDARD', max_length=126),
        ),
    ]
