# Generated by Django 3.0.2 on 2023-12-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0141_auto_20231222_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='second_pass_word',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='report_type',
            field=models.CharField(choices=[('PROTOCOL', 'PROTOCOL'), ('REPORT', 'REPORT'), ('CONDENSED_REPORT', 'CONDENSED_REPORT'), ('SECONDPASS', 'SECONDPASS'), ('APPENDIX_E2', 'APPENDIX_E2'), ('ARTICLE_REVIEWS', 'ARTICLE_REVIEWS'), ('PRISMA', 'PRISMA'), ('SECOND_PASS_WORD', 'SECOND_PASS_WORD')], default='REPORT', max_length=30),
        ),
    ]
