# Generated by Django 3.0.2 on 2023-12-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0140_auto_20231227_1119'),
        ('lit_reviews', '0142_auto_20231223_1855'),
    ]

    operations = [
    ]
