# Generated by Django 3.0.2 on 2024-01-14 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0143_merge_20231227_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtermpreview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='literaturereviewsearchproposalreport',
            name='status',
            field=models.CharField(choices=[('UPDATED', 'UPDATED'), ('FETCHING_PREVIEW', 'FETCHING_PREVIEW'), ('PROCESSING', 'PROCESSING'), ('FAILED', 'FAILED')], default='UPDATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='searchtermpreview',
            name='status',
            field=models.CharField(choices=[('NOT RUN', 'NOT RUN'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='NOT RUN', max_length=32),
        ),
    ]
