# Generated by Django 3.0.2 on 2024-01-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0144_auto_20240114_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturereviewsearchproposal',
            name='is_sota_term',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
