# Generated by Django 3.0.2 on 2024-01-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0145_auto_20240122_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturereviewsearchproposal',
            name='is_sota_term',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
