# Generated by Django 3.0.2 on 2024-02-28 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lit_reviews', '0145_articletag'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletag',
            name='article_reviews',
            field=models.ManyToManyField(to='lit_reviews.ArticleReview'),
        ),
        migrations.AddField(
            model_name='articletag',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
