# Generated by Django 3.0.2 on 2024-02-07 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0020_auto_20231031_1201'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lit_reviews', '0146_auto_20240122_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar_mode', models.CharField(choices=[('Basic', 'B'), ('Advanced', 'A')], default='B', max_length=126)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client_portal.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
