# Generated by Django 3.0.2 on 2024-02-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0146_auto_20240228_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='article_reviews',
            field=models.ManyToManyField(related_name='tags', to='lit_reviews.ArticleReview'),
        ),
    ]
