# Generated by Django 3.0.2 on 2024-02-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0147_projectconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectconfig',
            name='sidebar_mode',
            field=models.CharField(choices=[('B', 'Basic'), ('A', 'Advanced')], default='B', max_length=126),
        ),
    ]
