# Generated by Django 3.0.2 on 2024-02-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0148_auto_20240207_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtermspropssummaryreport',
            name='report_type',
            field=models.CharField(default='SEARCH_TERMS_SUMMARY', max_length=30),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='report_type',
            field=models.CharField(choices=[('PROTOCOL', 'PROTOCOL'), ('REPORT', 'REPORT'), ('CONDENSED_REPORT', 'CONDENSED_REPORT'), ('SECONDPASS', 'SECONDPASS'), ('APPENDIX_E2', 'APPENDIX_E2'), ('ARTICLE_REVIEWS', 'ARTICLE_REVIEWS'), ('PRISMA', 'PRISMA'), ('SECOND_PASS_WORD', 'SECOND_PASS_WORD'), ('FULL_TEXT_ZIP', 'FULL_TEXT_ZIP')], default='REPORT', max_length=30),
        ),
    ]
