# Generated by Django 3.0.2 on 2024-03-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0150_auto_20240227_1226'),
        ('lit_reviews', '0147_auto_20240228_1610'),
    ]

    operations = [
    ]
