# Generated by Django 3.0.2 on 2024-03-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0152_auto_20240325_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereviewsearchproposalreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
