# Generated by Django 3.0.2 on 2024-04-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0153_literaturereviewsearchproposalreport_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbidatabase',
            name='auto_search_available',
            field=models.BooleanField(default=False, help_text='Auto Search Scraper available in this database ?'),
        ),
    ]
