# Generated by Django 3.0.2 on 2024-04-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0154_ncbidatabase_auto_search_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlereview',
            name='exclusion_comment',
            field=models.TextField(blank=True, help_text='Extra comment can be added to excluded articles only', null=True),
        ),
        migrations.AlterField(
            model_name='articlereview',
            name='notes',
            field=models.TextField(blank=True, help_text='general notes attached to the article review', null=True),
        ),
    ]
