# Generated by Django 3.0.2 on 2024-05-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0155_auto_20240416_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverseevent',
            name='brand_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
