# Generated by Django 3.0.2 on 2024-05-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0135_article_highlighted_full_text'),
        ('lit_reviews', '0156_adverseevent_brand_name'),
    ]

    operations = [
    ]
