# Generated by Django 3.0.2 on 2024-05-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0156_article_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.CharField(max_length=512, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
