# Generated by Django 3.0.2 on 2024-05-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0158_auto_20240522_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
