# Generated by Django 3.0.2 on 2024-05-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0159_auto_20240522_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchparameter',
            name='type',
            field=models.CharField(choices=[('NB', 'NUMBER'), ('TX', 'Text'), ('DP', 'Drop Down'), ('CK', 'Check Box'), ('DT', 'Date')], max_length=512),
        ),
    ]
