# Generated by Django 3.0.2 on 2024-05-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0160_auto_20240522_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.TextField(blank=True, help_text="article keywords collected from the uploaded file will be a string seperated by ','", null=True),
        ),
    ]
