# Generated by Django 3.0.2 on 2024-06-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0157_merge_20240528_1106'),
        ('lit_reviews', '0161_article_keywords'),
    ]

    operations = [
    ]
