# Generated by Django 3.0.2 on 2024-07-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0163_auto_20240624_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='audit_tracking_logs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='report_type',
            field=models.CharField(choices=[('PROTOCOL', 'PROTOCOL'), ('REPORT', 'REPORT'), ('CONDENSED_REPORT', 'CONDENSED_REPORT'), ('SECONDPASS', 'SECONDPASS'), ('APPENDIX_E2', 'APPENDIX_E2'), ('ARTICLE_REVIEWS', 'ARTICLE_REVIEWS'), ('PRISMA', 'PRISMA'), ('SECOND_PASS_WORD', 'SECOND_PASS_WORD'), ('FULL_TEXT_ZIP', 'FULL_TEXT_ZIP'), ('TERMS_SUMMARY', 'TERMS_SUMMARY'), ('SEARCH_VALIDATION_ZIP', 'SEARCH_VALIDATION_ZIP'), ('DUPLICATES', 'DUPLICATES'), ('AUDIT_TRACKING_LOGS', 'AUDIT_TRACKING_LOGS')], default='REPORT', max_length=30),
        ),
    ]
