# Generated by Django 3.0.2 on 2024-07-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0162_merge_20240622_2221'),
        ('lit_reviews', '0163_auto_20240624_1330'),
    ]

    operations = [
    ]
