# Generated by Django 3.0.2 on 2024-07-08 15:54
from django.contrib.postgres.operations import HStoreExtension
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0164_merge_20240701_2149'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='literaturesearch',
            name='advanced_options',
            field=django.contrib.postgres.fields.hstore.HStoreField(help_text='\n            Storing Extra searching parameters that are specific per each field below list of params:\n            1. search_field: for clinical trials and maude we can search using different fields rather \n            than just a term text query, the default is the term query for clinical trials and product code for maude.\n        ', null=True),
        ),
    ]
