# Generated by Django 4.2 on 2024-07-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0165_comment"),
        ("lit_reviews", "0165_literaturesearch_advanced_options"),
    ]

    operations = []
