# Generated by Django 4.2 on 2024-07-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0164_auto_20240711_0056"),
        ("lit_reviews", "0171_alter_article_meta_data"),
    ]

    operations = []
