# Generated by Django 4.2 on 2024-07-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0166_alter_adversdatabasesummary_id_and_more"),
        ("lit_reviews", "0172_merge_20240719_0940"),
    ]

    operations = []
