# Generated by Django 4.2 on 2024-07-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0163_auto_20240716_1516"),
        ("lit_reviews", "0173_merge_20240719_1031"),
    ]

    operations = []
