# Generated by Django 4.2 on 2024-07-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0175_alter_finallreportjob_report_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="finallreportjob",
            name="article_reviews_ris",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="finallreportjob",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("PROTOCOL", "PROTOCOL"),
                    ("REPORT", "REPORT"),
                    ("CONDENSED_REPORT", "CONDENSED_REPORT"),
                    ("SECONDPASS", "SECONDPASS"),
                    ("APPENDIX_E2", "APPENDIX_E2"),
                    ("ARTICLE_REVIEWS", "ARTICLE_REVIEWS"),
                    ("ARTICLE_REVIEWS_RIS", "ARTICLE_REVIEWS_RIS"),
                    ("PRISMA", "PRISMA"),
                    ("SECOND_PASS_WORD", "SECOND_PASS_WORD"),
                    ("SECOND_PASS_RIS", "SECOND_PASS_RIS"),
                    ("FULL_TEXT_ZIP", "FULL_TEXT_ZIP"),
                    ("TERMS_SUMMARY", "TERMS_SUMMARY"),
                    ("SEARCH_VALIDATION_ZIP", "SEARCH_VALIDATION_ZIP"),
                    ("DUPLICATES", "DUPLICATES"),
                    ("AUDIT_TRACKING_LOGS", "AUDIT_TRACKING_LOGS"),
                ],
                default="REPORT",
                max_length=30,
            ),
        ),
    ]
