# Generated by Django 4.2 on 2024-08-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0176_finallreportjob_article_reviews_ris_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_company",
            field=models.BooleanField(
                default=True,
                help_text="If the client is a company multiple citemed users can be attached to his company",
                verbose_name="Citemed.io customer",
            ),
        ),
    ]
