# Generated by Django 4.2 on 2024-08-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0177_client_is_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="ncbidatabase",
            name="is_external",
            field=models.BooleanField(
                default=False,
                help_text="external databases are not supported by citemed and only available for direct citation imports",
            ),
        ),
    ]
