# Generated by Django 4.2 on 2024-08-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0177_client_is_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ris_file_fields",
                    models.CharField(
                        default='["A1", "A2", "A3", "A4", "AB", "AD", "AN", "AU", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "CA", "CN", "CY", "DA", "DB", "DO", "DP", "EP", "ER", "ET", "ID", "IS", "J2", "JA", "JF", "JO", "KW", "L1", "L2", "L4", "LA", "LB", "M1", "M3", "N1", "N2", "NV", "OP", "PB", "PY", "RI", "RN", "RP", "SE", "SN", "SP", "ST", "T1", "T2", "T3", "TA", "TI", "TT", "TY", "UK", "UR", "VL", "Y1", "Y2"]',
                        max_length=1024,
                    ),
                ),
                ("ris_article_title", models.CharField(default="TI", max_length=12)),
                ("ris_article_abstract", models.CharField(default="AB", max_length=12)),
                (
                    "ris_article_search_term_index",
                    models.CharField(default="RN", max_length=12),
                ),
                ("ris_article_state", models.CharField(default="LB", max_length=12)),
                ("ris_article_notes", models.CharField(default="N1", max_length=12)),
                ("ris_article_doi", models.CharField(default="DO", max_length=12)),
                ("ris_article_keywords", models.CharField(default="KW", max_length=12)),
                (
                    "ris_article_publication_year",
                    models.CharField(default="PY", max_length=12),
                ),
                (
                    "ris_article_journal_name",
                    models.CharField(default="JO", max_length=12),
                ),
                ("ris_article_urls", models.CharField(default="UR", max_length=12)),
                ("ris_articles_authors", models.CharField(default="AU", max_length=12)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lit_reviews.client",
                    ),
                ),
            ],
        ),
    ]
