# Generated by Django 4.2 on 2024-09-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0178_customersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="finallreportjob",
            name="is_simple",
            field=models.BooleanField(default=False),
        ),
    ]
