# Generated by Django 4.2 on 2024-08-27 12:56

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0178_ncbidatabase_is_external"),
    ]

    operations = [
        migrations.AlterField(
            model_name="literaturesearch",
            name="advanced_options",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True,
                help_text="\n            Storing Extra searching parameters that are specific per each field below list of params:\n            1. search_field: for clinical trials and maude we can search using different fields rather \n            than just a term text query, the default is the term query for clinical trials and product code for maude.\n        ",
                null=True,
            ),
        ),
    ]
