# Generated by Django 4.2 on 2024-09-08 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0178_customersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "RUNNING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="COMPLETED",
                        max_length=52,
                    ),
                ),
                ("duplicates_count", models.IntegerField(null=True)),
                (
                    "literature_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lit_reviews.literaturereview",
                    ),
                ),
            ],
        ),
    ]
