# Generated by Django 4.2 on 2024-09-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0178_customersettings"),
        ("lit_reviews", "0179_alter_literaturesearch_advanced_options"),
    ]

    operations = []
