# Generated by Django 4.2 on 2024-09-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0179_duplicationreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duplicationreport",
            name="duplicates_count",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
