# Generated by Django 4.2 on 2024-09-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0179_alter_literaturesearch_advanced_options"),
        ("lit_reviews", "0180_alter_duplicationreport_duplicates_count"),
    ]

    operations = []
