# Generated by Django 4.2 on 2024-09-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0181_merge_20240916_1159"),
    ]

    operations = [
        migrations.AddField(
            model_name="duplicationreport",
            name="needs_update",
            field=models.BooleanField(
                default=True,
                help_text="whithin a project whenever a new article is imported this should be updated to true",
            ),
        ),
    ]
