# Generated by Django 4.2 on 2024-09-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0179_finallreportjob_is_simple"),
        ("lit_reviews", "0180_merge_20240915_1737"),
        ("lit_reviews", "0180_merge_20240916_1451"),
        ("lit_reviews", "0182_duplicationreport_needs_update"),
    ]

    operations = []
