# Generated by Django 4.2 on 2024-09-23 12:27

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0183_merge_20240923_1227"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="meta_data",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True,
                help_text="\n            Storing Extra article fields that may not neccesary exists in all database / file formats\n            will try to list below as many fields as I can and from where we're getting them:\n            \n            Field Name    |   Description                              | File Format (we can extract from) \n\n            volume        |   Volume (VL)                              | RIS \n\n            volume_number |   issue or number of volumes.(IS)          | RIS \n\n            start_page    |   Start Page (SP)                          | RIS \n\n            end_page      |   End Page(EP)                             | RIS \n      \n        ",
                null=True,
            ),
        ),
    ]
