# Generated by Django 4.2 on 2024-10-14 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0184_alter_article_meta_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="literaturereview",
            name="cloned_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lit_reviews.literaturereview",
            ),
        ),
        migrations.AddField(
            model_name="literaturereview",
            name="is_cloning_completed",
            field=models.BooleanField(default=True),
        ),
    ]
