# Generated by Django 4.2 on 2024-10-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0185_literaturereview_cloned_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="literaturereview",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
