# Generated by Django 4.2 on 2024-10-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0186_literaturereview_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="literaturereview",
            name="cloning_errors",
            field=models.TextField(
                help_text="if the clone fails store any errors here", null=True
            ),
        ),
    ]
