# Generated by Django 4.2 on 2024-11-05 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0187_literaturereview_cloning_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
