# Generated by Django 4.2 on 2024-11-05 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0188_literaturereview_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturereview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
