# Generated by Django 4.2 on 2024-11-16 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0189_alter_literaturereview_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchLabelOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField()),
                (
                    "customer_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_label_options",
                        to="lit_reviews.customersettings",
                    ),
                ),
            ],
        ),
    ]
