# Generated by Django 4.2 on 2024-11-17 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0189_alter_literaturereview_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicatesGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duplicates",
                    models.ManyToManyField(
                        related_name="duplicates_articles",
                        to="lit_reviews.articlereview",
                    ),
                ),
                (
                    "original_article_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lit_reviews.articlereview",
                    ),
                ),
            ],
        ),
    ]
