# Generated by Django 4.2 on 2024-11-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0189_alter_literaturereview_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_unique_id',
            field=models.CharField(help_text='A unique id is created to identify identifical articles for the same client across multiple literature reviews', max_length=256, null=True),
        ),
    ]
