# Generated by Django 4.2 on 2024-11-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0190_duplicatesgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlereview",
            name="is_potential_duplicate",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
