# Generated by Django 4.2 on 2024-11-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0190_searchlabeloption"),
    ]

    operations = [
        migrations.AddField(
            model_name="literaturesearch",
            name="search_label",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
