# Generated by Django 4.2 on 2024-11-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0191_literaturesearch_search_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="literaturereviewsearchproposal",
            name="search_label",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
