# Generated by Django 4.2 on 2024-11-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0191_articlereview_is_potential_duplicate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlereview",
            name="is_potential_duplicate",
        ),
        migrations.AddField(
            model_name="articlereview",
            name="potential_duplicate_for",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to a potential duplicate article review.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="potential_duplicate_review",
                to="lit_reviews.articlereview",
            ),
        ),
    ]
