# Generated by Django 4.2 on 2024-11-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0190_article_article_unique_id'),
        ('lit_reviews', '0192_remove_articlereview_is_potential_duplicate_and_more'),
    ]

    operations = [
    ]
