# Generated by Django 4.2 on 2024-11-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0192_literaturereviewsearchproposal_search_label'),
        ('lit_reviews', '0194_articletag_articles_alter_article_meta_data'),
    ]

    operations = [
    ]
