# Generated by Django 4.2 on 2024-11-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0195_merge_20241127_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='full_texts_naming_format',
            field=models.CharField(choices=[('A', 'Authors - Year Of Publication - First Pieces of the Title'), ('B', 'First Pieces of the Title - Authors - Year Of Publication'), ('C', 'Year Of Publication - Authors - First Pieces of the Title')], default='A', max_length=112),
        ),
    ]
