# Generated by Django 4.2 on 2024-11-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0193_merge_20241126_1315'),
        ('lit_reviews', '0196_customersettings_full_texts_naming_format'),
    ]

    operations = [
    ]
