# Generated by Django 4.2 on 2025-01-20 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lit_reviews', '0197_merge_20241128_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturereview',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='literaturereview',
            name='cloning_errors',
            field=models.TextField(blank=True, help_text='if the clone fails store any errors here', null=True),
        ),
    ]
