# Generated by Django 4.2 on 2025-01-11 12:19

from django.db import migrations, models
import lit_reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0197_merge_20241128_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finallreportjob',
            name='all_articles_review',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='appendix_e2',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='article_reviews_ris',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='audit_tracking_logs',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='condensed_report',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='duplicates_report',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='fulltext_zip',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='missing_clinical_appraisals',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='protocol',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='second_pass_articles',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='second_pass_ris',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='second_pass_word',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='terms_summary_report',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='verification_zip',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='vigilance_report',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
    ]
