# Generated by Django 4.2 on 2025-01-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0197_merge_20241128_1826"),
    ]

    operations = [
        migrations.AddField(
            model_name="literaturesearch",
            name="is_notebook_search",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
