# Generated by Django 4.2 on 2025-01-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0198_alter_literaturereview_authorized_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlereview',
            name='processed_title',
            field=models.CharField(blank=True, max_length=5025, null=True),
        ),
    ]
