# Generated by Django 4.2 on 2025-02-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0198_literaturesearch_is_notebook_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereview',
            name='is_notebook',
            field=models.BooleanField(default=False, help_text='A notebook Project are only for testing different search terms and check thier results, we should have one notebook project per client'),
        ),
    ]
