# Generated by Django 4.2 on 2025-02-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0199_articlereview_processed_title'),
        ('lit_reviews', '0199_literaturereview_is_notebook'),
    ]

    operations = [
    ]
