# Generated by Django 4.2 on 2025-02-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0200_merge_20250201_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturesearch',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
