# Generated by Django 4.2 on 2025-02-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0201_literaturesearch_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_added_to_library',
            field=models.BooleanField(blank=True, default=False, help_text='\n        if the article is coming from notebook searches all are hidden by default \n        inside manage citations view, want to show them up? flag this as true\n        ', null=True),
        ),
    ]
