# Generated by Django 4.2 on 2025-02-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0198_alter_finallreportjob_all_articles_review_and_more'),
        ('lit_reviews', '0202_article_is_added_to_library'),
    ]

    operations = [
    ]
