# Generated by Django 4.2 on 2025-02-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0203_merge_20250207_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalextractionfield',
            name='extraction_field_number',
            field=models.SmallIntegerField(default=1, help_text='Each Appraisal Field can have multiple values (Sub Extractions), we can differentiate between the different values by their number the default value has number 1'),
        ),
    ]
