# Generated by Django 4.2 on 2025-02-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0204_appraisalextractionfield_extraction_field_number'),
        ('lit_reviews', '0205_finallreportjob_cumulative_report_and_more'),
    ]

    operations = [
    ]
