# Generated by Django 4.2 on 2025-04-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0206_merge_20250224_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalextractionfield',
            name='ai_value',
            field=models.CharField(blank=True, help_text='AI generated value for this extraction field', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='appraisalextractionfield',
            name='ai_value_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('edited', 'Edited'), ('rejected', 'Rejected'), ('not_reviewed', 'Not Reviewed')], default='not_reviewed', help_text='Status of the AI generated value - whether it was accepted, edited, rejected, or not reviewed', max_length=12),
        ),
    ]
