# Generated by Django 4.2 on 2025-04-20 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lit_reviews', '0206_merge_20250224_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturereview',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, help_text='Want to make this project accessible to external users that are not a company members? you can add them here', null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='literaturereview',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lit_reviews.client', verbose_name='Company'),
        ),
    ]
