# Generated by Django 4.2 on 2025-04-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit_reviews", "0206_merge_20250224_1942"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchconfiguration",
            name="config_type",
            field=models.CharField(
                choices=[("recommended", "Recommended"), ("manual", "Manual")],
                default="recommended",
                help_text="Indicates whether the configuration is recommended or manual.",
                max_length=20,
            ),
        ),
    ]
