# Generated by Django 4.2 on 2025-04-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0207_alter_literaturereview_authorized_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly'), ('quarterly', 'quarterly'), ('annually', 'annually')], default='weekly', max_length=32)),
                ('start_date', models.DateField()),
                ('alert_type', models.CharField(blank=True, choices=[('under_evaluation', 'Under Evaluation Only'), ('competitor', 'Competitor Only'), ('similar', 'Similar Only'), ('all', 'All Devices (Under, Competitor and Similar)')], help_text='Send alerts when device is found in articles', max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active reviews runs and create new projects on a regular bases in accordance with the selected interval')),
                ('competitor_devices', models.ManyToManyField(blank=True, null=True, related_name='competitor_livings', to='lit_reviews.device')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='under_evaluation_livings', to='lit_reviews.device')),
                ('project_protocol', models.ForeignKey(blank=True, help_text='copy protocol data and search terms from this project in the first run', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lit_reviews.literaturereview')),
                ('similar_devices', models.ManyToManyField(blank=True, null=True, related_name='similar_livings', to='lit_reviews.device')),
            ],
        ),
    ]
