# Generated by Django 4.2 on 2025-04-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0207_alter_literaturereview_authorized_users_and_more'),
        ('lit_reviews', '0207_searchconfiguration_config_type'),
    ]

    operations = [
    ]
