# Generated by Django 4.2 on 2025-04-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0207_appraisalextractionfield_ai_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionfield',
            name='field_label',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
