# Generated by Django 4.2 on 2025-04-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0208_extractionfield_field_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractionfield',
            old_name='field_label',
            new_name='ai_prompte',
        ),
    ]
