# Generated by Django 4.2 on 2025-05-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0208_livingreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereview',
            name='parent_living_review',
            field=models.ForeignKey(blank=True, help_text='was this created automatically for a living review?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='lit_reviews.livingreview'),
        ),
    ]
