# Generated by Django 4.2 on 2025-04-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0209_rename_field_label_extractionfield_ai_prompte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionfield',
            name='ai_prompte',
            field=models.TextField(blank=True, help_text='AI Prompte ll help generate and use ai models', max_length=512, null=True),
        ),
    ]
