# Generated by Django 4.2 on 2025-05-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0208_merge_20250425_1039'),
        ('lit_reviews', '0209_literaturereview_parent_living_review'),
    ]

    operations = [
    ]
