# Generated by Django 4.2 on 2025-04-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0210_alter_extractionfield_ai_prompte'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='ai_generation_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', help_text='Current status of AI extraction field generation for this appraisal', max_length=20),
        ),
        migrations.AddField(
            model_name='clinicalliteratureappraisal',
            name='ai_last_processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when AI last processed this appraisal', null=True),
        ),
    ]
