# Generated by Django 4.2 on 2025-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0211_clinicalliteratureappraisal_ai_generation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalextractionfield',
            name='ai_simplified_value',
            field=models.CharField(blank=True, help_text='AI simplified generated value for this extraction field', max_length=1024, null=True),
        ),
    ]
