# Generated by Django 4.2 on 2025-05-05 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0210_merge_20250501_1701'),
        ('lit_reviews', '0212_appraisalextractionfield_ai_simplified_value'),
    ]

    operations = [
    ]
