# Generated by Django 4.2 on 2025-07-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0213_merge_20250505_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlereview',
            name='ai_decision_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlereview',
            name='ai_exclusion_reason',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='articlereview',
            name='ai_state_decision',
            field=models.CharField(blank=True, choices=[('U', 'Unclassified'), ('I', 'Retained'), ('M', 'Maybe'), ('E', 'Excluded'), ('D', 'Duplicate')], max_length=1, null=True),
        ),
    ]
