# Generated by Django 4.2 on 2025-07-05 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lit_reviews', '0213_merge_20250505_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequestTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Detailed description of the issue or request')),
                ('demo_video', models.FileField(blank=True, help_text='Upload a demo video showing the issue', null=True, upload_to='support_tickets/videos/')),
                ('follow_up_option', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('teams', 'Teams Meeting')], default='email', help_text='Preferred method for follow-up communication', max_length=20)),
                ('ticket_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_for_response', 'Waiting for Response'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text='Current status of the support ticket', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('solved_date', models.DateTimeField(blank=True, help_text='Date when the ticket was resolved', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Request Ticket',
                'verbose_name_plural': 'Support Request Tickets',
                'ordering': ['-created_date'],
            },
        ),
    ]
