# Generated by Django 4.2 on 2025-06-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0213_merge_20250505_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlereview',
            name='full_text_status',
            field=models.CharField(blank=True, choices=[('uploaded', 'uploaded'), ('missing', 'missing'), ('excluded', 'excluded')], null=True),
        ),
    ]
