# Generated by Django 4.2 on 2025-07-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0214_articlereview_full_text_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='automatic_ai_extraction',
            field=models.BooleanField(default=False, help_text="Automatically extract study information from the Full Text PDF when it's uploaded"),
        ),
    ]
