# Generated by Django 4.2 on 2025-07-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0214_supportrequestticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequestticket',
            name='demo_video',
            field=models.URLField(blank=True, help_text='URL link to a demo video showing the issue (Loom)', null=True),
        ),
    ]
