# Generated by Django 4.2 on 2025-07-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0215_alter_supportrequestticket_demo_video'),
        ('lit_reviews', '0215_customersettings_automatic_ai_extraction'),
    ]

    operations = [
    ]
