# Generated by Django 4.2 on 2025-07-10 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0216_merge_20250710_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleReviewDeviceMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentions_count', models.IntegerField()),
                ('device_type', models.CharField(choices=[('similar', 'Similar'), ('competitor', 'competitor'), ('under_evaluation', 'Under Evaluation')])),
                ('article_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.articlereview')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_reviews.device')),
            ],
        ),
    ]
