# Generated by Django 4.2 on 2025-07-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0217_articlereviewdevicemention'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereview',
            name='is_living_review',
            field=models.BooleanField(default=False),
        ),
    ]
