# Generated by Django 4.2 on 2025-07-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0216_merge_20250714_1801'),
        ('lit_reviews', '0216_merge_20250715_1727'),
        ('lit_reviews', '0218_literaturereview_is_living_review'),
    ]

    operations = [
    ]
