# Generated by Django 4.2 on 2025-07-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0214_articlereview_ai_decision_accepted_and_more'),
        ('lit_reviews', '0219_merge_20250720_0953'),
    ]

    operations = [
    ]
