# Generated by Django 4.2 on 2025-07-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0220_merge_20250722_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionfield',
            name='field_section',
            field=models.CharField(choices=[('SO', 'Suitability and Outcomes (All Articles including SoTA)'), ('QC', 'Quality and Contribution Questions'), ('MR', 'MDCG Ranking'), ('EF', 'Extraction Fields'), ('ST', 'SoTa'), ('CS', 'Custom Section')], default='EF', max_length=10),
        ),
    ]
