# Generated by Django 4.2 on 2025-07-23 12:55

from django.db import migrations, models
import lit_reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0221_alter_extractionfield_field_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='finallreportjob',
            name='abbot_report',
            field=models.FileField(blank=True, null=True, upload_to=lit_reviews.models.unique_file_name),
        ),
        migrations.AlterField(
            model_name='finallreportjob',
            name='report_type',
            field=models.CharField(choices=[('PROTOCOL', 'PROTOCOL'), ('REPORT', 'REPORT'), ('ABBOTT_REPORT', 'ABBOTT_REPORT'), ('CONDENSED_REPORT', 'CONDENSED_REPORT'), ('SECONDPASS', 'SECONDPASS'), ('APPENDIX_E2', 'APPENDIX_E2'), ('ARTICLE_REVIEWS', 'ARTICLE_REVIEWS'), ('ARTICLE_REVIEWS_RIS', 'ARTICLE_REVIEWS_RIS'), ('PRISMA', 'PRISMA'), ('SECOND_PASS_WORD', 'SECOND_PASS_WORD'), ('SECOND_PASS_RIS', 'SECOND_PASS_RIS'), ('FULL_TEXT_ZIP', 'FULL_TEXT_ZIP'), ('TERMS_SUMMARY', 'TERMS_SUMMARY'), ('SEARCH_VALIDATION_ZIP', 'SEARCH_VALIDATION_ZIP'), ('DUPLICATES', 'DUPLICATES'), ('AUDIT_TRACKING_LOGS', 'AUDIT_TRACKING_LOGS'), ('DEVICE_HISTORY', 'DEVICE_HISTORY'), ('CUMULATIVE_REPORT', 'CUMULATIVE_REPORT')], default='REPORT', max_length=30),
        ),
    ]
