# Generated by Django 4.2 on 2025-07-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0222_finallreportjob_abbot_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalextractionfield',
            name='ai_value',
            field=models.CharField(blank=True, help_text='AI generated value for this extraction field', max_length=2048, null=True),
        ),
    ]
