# Generated by Django 4.2 on 2025-08-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_reviews', '0223_alter_appraisalextractionfield_ai_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturesearch',
            name='pico_category',
            field=models.CharField(blank=True, choices=[('P', 'Population'), ('I', 'Intervention'), ('C', 'Comparison'), ('O', 'Outcome')], max_length=1, null=True),
        ),
    ]
